language: dart

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

dart:
  - 2.3.2
  - stable
  - dev

script:
  - dartanalyzer .
  - dartfmt -n --set-exit-if-changed .
  - pub run dependency_validator -i build_config,pedantic
  - pub run test
