language: dart

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

dart:
  # TODO: uncomment this when we have a way to only run the dartfmt check on
  #       the stable channel of Dart
  # - 2.3.2
  - stable
  - dev

script:
  - dartanalyzer .
  - dartfmt -n --set-exit-if-changed .
  - pub run dependency_validator -i build_config,pedantic
  - pub run test
