include: package:workiva_analysis_options/v2.yaml
include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude:
    - example/**
    - lib/**.g.dart
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_types_on_closure_parameters
    - prefer_void_to_null
    - void_checks
