targets:
  $default:
    sources:
      include:
        - lib/**

builders:
  test_html_builder:
    import: "package:test_html_builder/builder.dart"
    builder_factories:
      - testHtmlBuilder
    build_extensions:
      $test$:
        - templates/default_template.html
        - test_html_builder_config.json
      $package$:
        - test/templates/default_template.html
        - test/test_html_builder_config.json
    auto_apply: root_package
    build_to: cache
    runs_before:
      - build_test:test_bootstrap
      - test_html_builder:aggregator
      - test_html_builder:dart_test_yaml
      - test_html_builder:templates
    applies_builders:
      - test_html_builder:aggregator
      - test_html_builder:dart_test_yaml
      - test_html_builder:templates

  test_html_builder:aggregator:
    import: "package:test_html_builder/builder.dart"
    builder_factories:
      - aggregateTestBuilder
    build_extensions:
      _template.html:
        - _template.browser_aggregate_test.dart
    build_to: source
    is_optional: true
    runs_before:
      - test_html_builder:dart_test_yaml
      - test_html_builder:templates
      - build_test:test_bootstrap
    defaults:
      generate_for:
        - test/**

  test_html_builder:templates:
    import: "package:test_html_builder/builder.dart"
    builder_factories:
      - templateBuilder
    build_extensions:
      _test.dart:
        - _test.html
    build_to: cache
    defaults:
      generate_for:
        - test/**

  test_html_builder:dart_test_yaml:
    import: "package:test_html_builder/builder.dart"
    builder_factories:
      - dartTestYamlBuilder
    build_extensions:
      $package$:
        - dart_test.browser_aggregate.yaml
        - test/dart_test.browser_aggregate.yaml
    build_to: source
