name: test_html_builder
version: 1.0.1
homepage: https://github.com/Workiva/test_html_builder

description: >
  Builder that generates HTML files from templates for dart tests.

authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  build: ^1.1.4
  build_config: '>=0.3.0 <0.5.0'
  glob: ^1.1.7
  json_annotation: ^3.0.0
  logging: ^0.11.3+2
  path: ^1.6.4

dev_dependencies:
  build_runner: ^1.3.0
  build_test: ^0.10.7+3
  build_web_compilers: ^2.3.0
  dependency_validator: ^1.2.0
  pedantic: ^1.8.0
  test: ^1.6.3

  # If changes are made to `lib/src/config.dart` and regeneration is needed,
  # uncomment this and comment out the test_html_builder definition in
  # `build.yaml`.
  # json_serializable: ^3.0.0
