name: test_html_builder
version: 0.0.0
private: true

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  build: ^1.1.4
  build_config: '>=0.3.0 <0.5.0'
  glob: ^1.1.7
  json_annotation: ^2.3.0

dev_dependencies:
  build_runner: ^1.3.0
  build_test: ^0.10.7+3
  build_web_compilers: '>=1.0.0 <3.0.0'
  dart_dev: ^2.0.0
  dart_style: ^1.2.4
  test: ^1.6.3

  # If changes are made to `lib/src/config.dart` and regeneration is needed,
  # uncomment this and comment out the test_html_builder definition in
  # `build.yaml`.
  # json_serializable: ^2.3.0
