name: test_html_builder_example_project
version: 0.0.0
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  test: ^1.8.0
  test_html_builder:
    path: ../..
