name: test_html_builder_example_project
version: 0.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^3.0.0
  test: ^1.17.12
  test_html_builder:
    path: ../..
