name: test_html_builder_example_project
version: 0.0.0
publish_to: none

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ">=0.10.9 <2.0.0"
  build_web_compilers: ^2.6.3
  meta: ">=1.2.2 <1.7.0" # Workaround to avoid https://github.com/dart-lang/sdk/issues/46142
  test: ^1.15.7
  test_html_builder:
    path: ../..
