name: test_html_builder_example_project
version: 0.0.0
publish_to: none

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ">=0.10.9 <2.0.0"
  build_web_compilers: ^2.6.3
  test: ^1.15.7
  test_html_builder:
    path: ../..
