name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
    tags:
      - '**'

jobs:
  build:
    uses: Workiva/gha-dart-oss/.github/workflows/build.yaml@v0.1.5

  checks:
    uses: Workiva/gha-dart-oss/.github/workflows/checks.yaml@v0.1.5

  test:
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.19.6, stable, beta ]
    uses: Workiva/gha-dart-oss/.github/workflows/test-unit.yaml@v0.1.5
    with:
      sdk: ${{ matrix.sdk }}

  example:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.19.6, stable, beta ]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Example consumer tests
        run: ./tool/test_example.sh
