name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.13.4, 2.18.7 ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Alias pub
        if: ${{ matrix.sdk == '2.18.7' }}
        run: echo -e '#!/bin/bash\ndart pub "$@"' > $DART_HOME/bin/pub && chmod u+x $DART_HOME/bin/pub
      - name: Install dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Check formatting
        run: dart format --set-exit-if-changed -o none .
        if: ${{ matrix.sdk == '2.13.4' }}
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
