name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.6
      - run: dart format --set-exit-if-changed -o none .
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # TODO: Add stable and beta sdk's as a separate effort (FEDX-1911)[https://jira.atl.workiva.net/browse/FEDX-1911]
        sdk: [ 2.19.6, stable, beta ]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart run dependency_validator
      - run: dart analyze
      - run: dart test test/lib
      - run: dart test test/bin
      - uses: anchore/sbom-action@v0
        if: ${{ matrix.sdk == 'stable' }}
        with:
          path: ./
          format: cyclonedx-json
  example:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # TODO: Add stable and beta sdk's as a separate effort (FEDX-1911)[https://jira.atl.workiva.net/browse/FEDX-1911]
        sdk: [ 2.19.6, stable, beta ]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Example consumer tests
        run: ./tool/test_example.sh
