name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ 2.7.2, stable, beta, dev ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: pub get
      - name: Validate dependencies
        run: pub run dependency_validator
      - name: Check formatting
        run: dartfmt -w .
        if: ${{ matrix.sdk == '2.7.2' }}
      - name: Analyze project source
        run: dartanalyzer .
      - name: Run tests
        run: pub run test
