name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  id-token: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.6
      - run: dart format --set-exit-if-changed -o none .
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.19.6, stable, beta ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart run dependency_validator
      - run: dart analyze
      - run: dart test test/lib
      - run: dart test test/bin
  skynet-test:
    name: Skynet Tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Upload Test Artifacts
        uses: Workiva/gha-upload-test-reports@v1.0.3
  example:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.19.6, stable, beta ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Example consumer tests
        run: ./tool/test_example.sh
